services:
  db:
    image: pgvector/pgvector:pg16
    container_name: foodfest-ai-chat-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - foodfest_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine  # Используем официальный, легковесный образ Redis
    container_name: foodfest-ai-chat-redis
    ports:
      - "6379:6379"  # Пробрасываем стандартный порт Redis на хост
    volumes:
      - foodfest_redis_data:/data  # Создаем том для сохранения данных Redis (очередей)
    restart: unless-stopped

volumes:
  foodfest_postgres_data:
  foodfest_redis_data:
